
export const benefitList=["arytmia","ból glowy","ból miesni i stawow","ból zeba","goraczka",
    "kaszel","nadcisnienie","nadwaga","niedowaga","problem ze wzrokiem",
    "uraz kosci","wysypka","wzdecia","zmeczenie","blady"];

export const benefitToRequest=[["ODDZIAŁ KARDIOCHIRURGICZNY","ODDZIAŁ KARDIOCHIRURGICZNY DLA DZIECI","ODDZIAŁ KARDIOLOGICZNY","ODDZIAŁ KARDIOLOGICZNY DLA DZIECI"],
    ["ODDZIAŁ NEUROCHIRURGICZNY DLA DZIECI","ODDZIAŁ NEUROLOGICZNY"],
    ["DZIAŁ (PRACOWNIA) FIZJOTERAPII","DZIAŁ (PRACOWNIA) FIZJOTERAPII DLA DZIECI","DZIAŁ (PRACOWNIA) FIZYKOTERAPII"],
    ["PORADNIA STOMATOLOGICZNA","PORADNIA STOMATOLOGICZNA DLA DZIECI"],
    ["OPIEKA DOMOWA  RODZINNA"],
    ["ODDZIAŁ REHABILITACJI PULMONOLOGICZNEJ","ODDZIAŁ REHABILITACJI PULMONOLOGICZNEJ DLA DZIECI"],
    ["ŚWIADCZENIA Z ZAKRESU KARDIOLOGII"],
    ["PORADNIA GASTROENTEROLOGICZNA","BADANIA GENETYCZNE","ODDZIAŁ ENDOKRYNOLOGICZNY","ODDZIAŁ ENDOKRYNOLOGICZNY DLA DZIECI"],
    ["PORADNIA GASTROENTEROLOGICZNA","BADANIA GENETYCZNE","ODDZIAŁ ENDOKRYNOLOGICZNY","ODDZIAŁ ENDOKRYNOLOGICZNY DLA DZIECI"],
    ["ODDZIAŁ OKULISTYCZNY","ODDZIAŁ OKULISTYCZNY DLA DZIECI"],
    ["ODDZIAŁ CHIRURGII URAZOWO-ORTOPEDYCZNEJ","ODDZIAŁ CHIRURGII URAZOWO-ORTOPEDYCZNEJ DLA DZIECI"],
    ["ODDZIAŁ ALERGOLOGICZNY","ODDZIAŁ ALERGOLOGICZNY DLA DZIECI","ODDZIAŁ DERMATOLOGICZNY","ODDZIAŁ DERMATOLOGICZNY DLA DZIECI"],
    ["ODDZIAŁ GASTROENTEROLOGICZNY","ODDZIAŁ GASTROENTEROLOGICZNY DLA DZIECI"],
    ["ODDZIAŁ HEMATOLOGICZNY","ODDZIAŁ HEMATOLOGICZNY DLA DZIECI"],
    ["ODDZIAŁ HEMATOLOGICZNY","ODDZIAŁ HEMATOLOGICZNY DLA DZIECI"]];
